/**
 * Embeddable verification badge (SVG).
 *
 * The distribution lever: a member drops this in their GitHub README, personal
 * site, or gist, and it links back to their verifiable profile. This is how
 * developer tools actually spread — shields.io proved the pattern.
 *
 * It is generated by the collector at publish time and written as a static file,
 * so it needs no server and stays consistent with the local-first architecture.
 *
 * HONESTY CONSTRAINTS (these are why the badge says what it says):
 *  - It reports ACTIVE DAYS, never token volume. A token count on a README would
 *    become exactly the vanity leaderboard this project refuses to be.
 *  - The word "verified" refers to the SIGNATURE, which is genuinely checkable —
 *    not to identity, skill, or quality.
 *  - Every value is drawn from the signed snapshot, so the badge cannot claim
 *    more than the profile does.
 */

export interface BadgeInput {
  activeDays: number;
  /** Rendered as the right-hand value; keep it short. */
  handle?: string;
  /** 'days' shows active AI-work days; 'verified' shows a plain verified mark. */
  variant?: 'days' | 'verified';
}

const LEFT_BG = '#1a2444';
const RIGHT_BG = '#0a7c3e';
const TEXT = '#ffffff';

/** Escape the five XML entities. Badge text comes from a signed snapshot, but
 *  this is rendered as markup, so it is escaped regardless. */
function esc(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/** Approximate advance width for 11px DejaVu-ish sans, good enough for layout. */
function textWidth(text: string): number {
  let w = 0;
  for (const ch of text) {
    if (/[ilj|.,:'!]/.test(ch)) w += 3.2;
    else if (/[A-Z0-9]/.test(ch)) w += 7.4;
    else if (/[mwMW]/.test(ch)) w += 9.6;
    else w += 6.3;
  }
  return Math.ceil(w);
}

export function renderBadge(input: BadgeInput): string {
  const label = 'TOKENS';
  const value =
    input.variant === 'verified'
      ? 'verified'
      : `${input.activeDays} active AI-work ${input.activeDays === 1 ? 'day' : 'days'}`;

  const padding = 10;
  const labelW = textWidth(label) + padding * 2;
  const valueW = textWidth(value) + padding * 2;
  const total = labelW + valueW;
  const height = 20;

  // Accessible name for screen readers; the <title> is what assistive tech reads.
  const title = `TOKENS: ${value} (signature verified)`;

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${total}" height="${height}" role="img" aria-label="${esc(title)}">
  <title>${esc(title)}</title>
  <linearGradient id="s" x2="0" y2="100%">
    <stop offset="0" stop-color="#fff" stop-opacity=".7"/>
    <stop offset=".1" stop-color="#aaa" stop-opacity=".1"/>
    <stop offset=".9" stop-color="#000" stop-opacity=".3"/>
    <stop offset="1" stop-color="#000" stop-opacity=".5"/>
  </linearGradient>
  <clipPath id="r"><rect width="${total}" height="${height}" rx="3" fill="#fff"/></clipPath>
  <g clip-path="url(#r)">
    <rect width="${labelW}" height="${height}" fill="${LEFT_BG}"/>
    <rect x="${labelW}" width="${valueW}" height="${height}" fill="${RIGHT_BG}"/>
    <rect width="${total}" height="${height}" fill="url(#s)"/>
  </g>
  <g fill="${TEXT}" text-anchor="middle" font-family="Verdana,DejaVu Sans,Geneva,sans-serif" font-size="11">
    <text x="${labelW / 2}" y="15" fill="#000" fill-opacity=".3">${esc(label)}</text>
    <text x="${labelW / 2}" y="14">${esc(label)}</text>
    <text x="${labelW + valueW / 2}" y="15" fill="#000" fill-opacity=".3">${esc(value)}</text>
    <text x="${labelW + valueW / 2}" y="14">${esc(value)}</text>
  </g>
</svg>
`;
}

/** Ready-to-paste embed snippets for the profile page. */
export function badgeSnippets(profileUrl: string, badgeUrl: string): { markdown: string; html: string } {
  return {
    markdown: `[![TOKENS verified](${badgeUrl})](${profileUrl})`,
    html: `<a href="${profileUrl}"><img src="${badgeUrl}" alt="TOKENS verified AI-work profile"></a>`,
  };
}
