/**
 * Embeddable badges (SVG) — "paper and ink".
 *
 * The distribution lever: a member drops one of these in their README or site and
 * it links back to their verifiable profile. Generated by the collector at publish
 * time as static files, so there is no server.
 *
 * WHY THIS DOES NOT LOOK LIKE A SHIELDS BADGE
 * The old badge was a shields.io clone: glossy two-tone chip, saturated green,
 * one fact. That grammar means "build passing" — approved, graded, scored. This
 * product refuses to grade people, so it should not borrow the visual language of
 * grading. This is a stamped ledger line instead: matte paper, ink, hairline
 * rules, a monospace date cell. No gloss, no gradient, and NO GREEN anywhere.
 *
 * The only saturated colour in the system is the failure red, on the faces where
 * a signature did not verify. That asymmetry is deliberate: a signature check is
 * the one genuinely binary thing here, and absence of alarm is not a checkmark.
 *
 * HONESTY CONSTRAINTS (why the badge says what it says):
 *  - Never token volume. A token count on a README is the vanity leaderboard this
 *    project refuses to be. BadgeFacts makes it structurally unrepresentable.
 *  - "signature verifiable", never "signature verified". This file is only written
 *    after self-verification passes, so it can never render its own failure; the
 *    past tense would be a lie of tense. "Verifiable" is an instruction to the
 *    reader and is true at the moment they read it.
 *  - No handle or display name on any face. A handle beside verification language
 *    reads as "verified identity", the inference the claim ladder exists to block.
 *    The handle lives in the LINK TARGET, where it cannot compose that claim.
 *  - No glyph may exceed 2x the smallest glyph on the same face. Type scale is a
 *    grading channel exactly like colour: a 32px number over an 8px disclaimer is
 *    the visual grammar of advertising fine print. Enforced by test.
 *  - The card states the active-day predicate. "96 active days" reads as a claim
 *    about hours worked; the measured predicate is "a day with at least one
 *    recorded session", and the gap is the largest inflation vector here.
 *  - The card states that the record is self-measured. The dark band and wordmark
 *    borrow the grammar of certificate authorities; without that line the artifact
 *    implies a third party audited something. Nobody did.
 *
 * RENDERING CONSTRAINTS (GitHub serves these through its camo proxy, as <img>):
 *  - No external references of any kind: no webfonts, no remote images, no CSS.
 *  - No script, no :hover, no <a>, no interactivity — all dead in <img> context.
 *  - textLength on EVERY <text>. Without it, a machine lacking Verdana renders a
 *    wider fallback face and the text spills out of its cell. This is the single
 *    most common way a hand-rolled badge breaks on someone else's machine.
 *  - Opaque background. README images render on a transparent backdrop, so a
 *    badge that assumes white is unreadable in dark mode.
 */

export type BadgeVariant = 'inline' | 'mark' | 'card';
export type BadgeSignatureState = 'verifiable' | 'unverified' | 'revoked';

/**
 * The complete input surface. Note what is absent and cannot be added without
 * changing this type: any token count, any cost, any score, ratio, rank, or
 * percentage. Honesty enforced by the compiler rather than by review.
 */
export interface BadgeFacts {
  /** Distinct days with at least one recorded session. NOT hours worked. */
  activeDays: number;
  /** The member's own calendar date at generation. Never the UTC date. */
  asOf: string;
  /** Last day with recorded activity. */
  lastActiveDate: string | null;
  /** First measured day. Card only, and only ever labelled "measurement begins". */
  firstActiveDate: string | null;
  /** e.g. ['Claude Code', 'Codex']. */
  toolsUsed: string[];
  /** Required. A badge that is not a link asserts without citing. */
  profileUrl: string;
  signature?: BadgeSignatureState;
  /** Active dates, used only for the card's presence strip. */
  activeDates?: string[];
}

// ---------------------------------------------------------------- palette ----
// Every pair below clears WCAG AA for normal text; most clear AAA.
const L = {
  band: '#12161C',
  onBand: '#FFFFFF',
  paper: '#F6F4EF',
  paper2: '#EAE6DC',
  ink: '#12161C',
  ink2: '#4A5462',
  rule: '#C9C3B5',
} as const;
const D = {
  band: '#0B0E13',
  onBand: '#E9E7E2',
  paper: '#161A21',
  paper2: '#1E242D',
  ink: '#E9E7E2',
  ink2: '#9AA4B2',
  rule: '#2E3542',
} as const;
const FAIL_L = '#8C2F26';
const FAIL_D = '#C2564B';

const SANS = 'Verdana,DejaVu Sans,Geneva,sans-serif';
const MONO = 'ui-monospace,DejaVu Sans Mono,Menlo,Consolas,monospace';

function esc(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Approximate Verdana advance width. It only needs to be close: every <text> is
 * emitted with textLength, which forces the renderer to match this number
 * exactly, so a small error shifts letter spacing instead of overflowing a cell.
 */
export function textWidth(text: string, fontSize: number): number {
  let units = 0;
  for (const ch of text) {
    if (/[ .,:;'`|!ilj]/.test(ch)) units += 0.34;
    else if (/[ftIJr()[\]{}/\\-]/.test(ch)) units += 0.44;
    else if (/[A-Z]/.test(ch)) units += 0.72;
    else if (/[mwMW@]/.test(ch)) units += 0.94;
    else units += 0.6;
  }
  return Math.ceil(units * fontSize);
}
/** Monospace advance: uniform 0.6em. */
function monoWidth(text: string, fontSize: number): number {
  return Math.ceil([...text].length * fontSize * 0.6);
}
/** Odd widths align better to the pixel grid (shields does the same). */
function oddUp(n: number): number {
  const r = Math.ceil(n);
  return r % 2 === 0 ? r + 1 : r;
}

interface TextOpts {
  x: number;
  y: number;
  size: number;
  width: number;
  cls: string;
  mono?: boolean;
  anchor?: 'start' | 'middle' | 'end';
  weight?: number;
  spacing?: number;
}
/** A <text> that is guaranteed to occupy exactly `width`. */
function text(content: string, o: TextOpts): string {
  const attrs = [
    `x="${o.x}"`,
    `y="${o.y}"`,
    `class="${o.cls}"`,
    `font-family="${o.mono ? MONO : SANS}"`,
    `font-size="${o.size}"`,
    o.weight ? `font-weight="${o.weight}"` : '',
    o.spacing ? `letter-spacing="${o.spacing}"` : '',
    o.anchor && o.anchor !== 'start' ? `text-anchor="${o.anchor}"` : '',
    `textLength="${Math.max(1, Math.round(o.width))}"`,
  ].filter(Boolean);
  return `<text ${attrs.join(' ')}>${esc(content)}</text>`;
}

/** Theme-aware CSS. Presentation fallbacks are the light values, so a renderer
 *  that ignores <style> still produces a correct light badge.
 *
 *  The failure colour is only DEFINED on a failing badge. A passing badge that
 *  shipped a red rule it never used would still be carrying a pass/fail palette,
 *  and the point of the asymmetry is that there is no "pass" colour at all. */
function styleBlock(failed: boolean): string {
  return `<style>
    .band{fill:${L.band}} .onband{fill:${L.onBand}} .paper{fill:${L.paper}}
    .paper2{fill:${L.paper2}} .ink{fill:${L.ink}} .ink2{fill:${L.ink2}} .rule{fill:${L.rule}}
    ${failed ? `.fail{fill:${FAIL_L}}` : ''}
    @media (prefers-color-scheme:dark){
      .band{fill:${D.band}} .onband{fill:${D.onBand}} .paper{fill:${D.paper}}
      .paper2{fill:${D.paper2}} .ink{fill:${D.ink}} .ink2{fill:${D.ink2}} .rule{fill:${D.rule}}
      ${failed ? `.fail{fill:${FAIL_D}}` : ''}
    }
  </style>`;
}

function plural(n: number, one: string, many: string): string {
  return n === 1 ? one : many;
}

// ------------------------------------------------------------- 20px faces ----
const H = 20;
const PAD = 8;

/**
 * A three-cell stamped line: wordmark | subject | date.
 *
 * The third cell is always the as-of date. Keeping it constant across variants
 * is what makes this read as a postmark rather than a status chip — and it means
 * every face carries its own freshness, so a stale badge looks stale.
 */
function face(cells: { label: string; subject: string; asOf: string }, facts: BadgeFacts): string {
  const failed = facts.signature === 'unverified' || facts.signature === 'revoked';
  const F_SIZE = 10.5;
  const M_SIZE = 9.5;

  const w1 = oddUp(textWidth(cells.label, F_SIZE) + 1.2 * cells.label.length + PAD * 2);
  const w2 = oddUp(textWidth(cells.subject, F_SIZE) + PAD * 2);
  const w3 = oddUp(monoWidth(cells.asOf, M_SIZE) + PAD * 2);
  const total = w1 + w2 + w3;

  const title = `Ledger — ${cells.subject}, as of ${cells.asOf}`;
  const subjectFill = failed ? 'fail' : 'ink';

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${total}" height="${H}" viewBox="0 0 ${total} ${H}" role="img" aria-label="${esc(title)}">
  <title>${esc(title)}</title>
  ${styleBlock(failed)}
  <clipPath id="c"><rect width="${total}" height="${H}" rx="3"/></clipPath>
  <g clip-path="url(#c)" shape-rendering="crispEdges">
    <rect width="${total}" height="${H}" class="paper" fill="${L.paper}"/>
    <rect width="${w1}" height="${H}" class="band" fill="${L.band}"/>
    <rect x="${w1 + w2}" width="${w3}" height="${H}" class="paper2" fill="${L.paper2}"/>
    <rect x="${w1 + w2}" width="1" height="${H}" class="rule" fill="${L.rule}"/>
  </g>
  <g>
    ${text(cells.label, { x: w1 / 2, y: 13.6, size: F_SIZE, width: textWidth(cells.label, F_SIZE) + 1.2 * cells.label.length, cls: 'onband', anchor: 'middle', weight: 700, spacing: 1.2 })}
    ${text(cells.subject, { x: w1 + w2 / 2, y: 13.6, size: F_SIZE, width: textWidth(cells.subject, F_SIZE), cls: subjectFill, anchor: 'middle' })}
    ${text(cells.asOf, { x: w1 + w2 + w3 / 2, y: 13.4, size: M_SIZE, width: monoWidth(cells.asOf, M_SIZE), cls: 'ink2', anchor: 'middle', mono: true })}
  </g>
</svg>
`;
}

// ------------------------------------------------------------------ card ----
/**
 * 420px wide so it renders 1:1 inside GitHub's 419px mobile content column.
 * Anything wider gets silently downscaled by `max-width:100%` and the small type
 * falls off the legibility cliff.
 */
const CARD_W = 420;
export const CARD_INNER = CARD_W - 32;

/** Presence strip: one column per day, bounded at lastActiveDate.
 *  Three states, and "before measurement began" deliberately draws NOTHING —
 *  rendering unmeasured days as empty cells says something false about someone
 *  who started last week. */
function presenceStrip(facts: BadgeFacts, x: number, y: number, w: number, h: number): string {
  const { firstActiveDate, lastActiveDate } = facts;
  const dates = facts.activeDates ?? [];
  if (!firstActiveDate || !lastActiveDate || dates.length === 0) return '';

  const start = Date.parse(`${firstActiveDate}T00:00:00Z`);
  const end = Date.parse(`${lastActiveDate}T00:00:00Z`);
  if (Number.isNaN(start) || Number.isNaN(end) || end < start) return '';

  const days = Math.round((end - start) / 86_400_000) + 1;
  const active = new Set(dates);
  const cols = Math.min(days, Math.floor(w / 2));
  const perCol = days / cols;
  // Cap the column width. Without this, a member measured for a single day gets
  // one column stretched across the whole strip — a solid bar that reads as
  // "active throughout" when it means the exact opposite. A short history should
  // draw a short strip.
  const cw = Math.min(w / cols, 4);
  const drawnW = cw * cols;

  const marks: string[] = [];
  for (let i = 0; i < cols; i += 1) {
    const from = Math.floor(i * perCol);
    const to = Math.floor((i + 1) * perCol);
    let hit = false;
    for (let d = from; d < Math.max(to, from + 1) && !hit; d += 1) {
      const day = new Date(start + d * 86_400_000).toISOString().slice(0, 10);
      if (active.has(day)) hit = true;
    }
    if (hit) marks.push(`<rect x="${(x + i * cw).toFixed(2)}" y="${y}" width="${Math.max(1, cw - 0.9).toFixed(2)}" height="${h}" class="ink2" fill="${L.ink2}"/>`);
  }
  // The baseline rule spans only the measured period, not the card, so the strip
  // never implies a window the member has not actually been measured for.
  return `<g shape-rendering="crispEdges">
    <rect x="${x}" y="${y + h - 0.5}" width="${drawnW.toFixed(2)}" height="0.5" class="rule" fill="${L.rule}"/>
    ${marks.join('')}
  </g>`;
}

function renderCard(facts: BadgeFacts): string {
  const failed = facts.signature === 'unverified' || facts.signature === 'revoked';
  const BAND_H = 26;
  // Scale rule: largest glyph (16) is under 2x the smallest (11). The disclaimer
  // is not allowed to be fine print relative to the claim.
  const BIG = 16;
  const SMALL = 11;
  const META = 11;

  const countLine = `${facts.activeDays} active AI-work ${plural(facts.activeDays, 'day', 'days')}`;
  const tools = facts.toolsUsed.length ? facts.toolsUsed.join(' · ') : 'no tools recorded';
  const begins = facts.firstActiveDate ? `measurement begins ${facts.firstActiveDate}` : 'measurement window unknown';
  const last = facts.lastActiveDate ? `last recorded ${facts.lastActiveDate}` : 'nothing recorded yet';

  // Kept short enough to fit CARD_INNER at SMALL. textLength forces the rendered
  // advance to match the measured width, so a string that measures too wide does
  // not wrap — it silently runs off the card. Guarded by badge.test.ts.
  const notes = [
    'An active day is any day with at least one recorded session.',
    'It is not a measure of hours or effort.',
    'Self-measured on this device. No third party checked it.',
    'The signature shows the record was not altered after signing.',
    'It does not show identity, skill, quality, or authorship.',
  ];

  const stripY = 96;
  const stripH = 10;
  const notesY = 138;
  const NOTE_LEADING = 15;
  const H_CARD = notesY + notes.length * NOTE_LEADING + 24;
  const sigLine = failed
    ? facts.signature === 'revoked'
      ? 'signing key was revoked'
      : 'signature did not verify'
    : 'signature verifiable at ledger.imagineqira.com/verify';

  const title = `Ledger — ${countLine}, as of ${facts.asOf}`;

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${CARD_W}" height="${H_CARD}" viewBox="0 0 ${CARD_W} ${H_CARD}" role="img" aria-label="${esc(title)}">
  <title>${esc(title)}</title>
  ${styleBlock(failed)}
  <clipPath id="cc"><rect width="${CARD_W}" height="${H_CARD}" rx="4"/></clipPath>
  <g clip-path="url(#cc)">
    <rect width="${CARD_W}" height="${H_CARD}" class="paper" fill="${L.paper}"/>
    <rect width="${CARD_W}" height="${BAND_H}" class="band" fill="${L.band}"/>
    <rect y="${BAND_H}" width="${CARD_W}" height="1" class="rule" fill="${L.rule}" shape-rendering="crispEdges"/>
    ${text('LEDGER', { x: 16, y: 17.5, size: 11, width: textWidth('LEDGER', 11) + 7, cls: 'onband', weight: 700, spacing: 1.4 })}
    ${text('SIGNED SNAPSHOT · Ed25519', { x: CARD_W - 16, y: 17.5, size: 9.5, width: textWidth('SIGNED SNAPSHOT · Ed25519', 9.5), cls: 'onband', anchor: 'end', mono: true })}

    ${text(countLine, { x: 16, y: 58, size: BIG, width: textWidth(countLine, BIG), cls: failed ? 'fail' : 'ink' })}
    ${text(tools, { x: 16, y: 78, size: META, width: textWidth(tools, META), cls: 'ink2' })}

    ${presenceStrip(facts, 16, stripY, CARD_W - 32, stripH)}
    ${text(begins, { x: 16, y: stripY + stripH + 13, size: SMALL, width: textWidth(begins, SMALL), cls: 'ink2' })}
    ${text(last, { x: CARD_W - 16, y: stripY + stripH + 13, size: SMALL, width: textWidth(last, SMALL), cls: 'ink2', anchor: 'end' })}

    ${notes
      .map((n, i) => text(n, { x: 16, y: notesY + i * NOTE_LEADING, size: SMALL, width: textWidth(n, SMALL), cls: 'ink2' }))
      .join('\n    ')}

    <rect x="16" y="${H_CARD - 26}" width="${CARD_W - 32}" height="0.5" class="rule" fill="${L.rule}" shape-rendering="crispEdges"/>
    ${text(sigLine, { x: 16, y: H_CARD - 10, size: SMALL, width: textWidth(sigLine, SMALL), cls: failed ? 'fail' : 'ink2' })}
    ${text(facts.asOf, { x: CARD_W - 16, y: H_CARD - 10, size: SMALL, width: monoWidth(facts.asOf, SMALL), cls: 'ink2', anchor: 'end', mono: true })}
  </g>
</svg>
`;
}

// ----------------------------------------------------------------- public ----
export function renderBadge(facts: BadgeFacts, variant: BadgeVariant = 'inline'): string {
  if (!facts.profileUrl || !/^https?:\/\//i.test(facts.profileUrl)) {
    // A badge that does not link to its evidence is an assertion without a
    // citation, which is the thing this product exists to replace.
    throw new Error('renderBadge: profileUrl is required and must be absolute');
  }
  const state = facts.signature ?? 'verifiable';
  const subjectFor = (ok: string): string =>
    state === 'revoked' ? 'signing key revoked' : state === 'unverified' ? 'signature did not verify' : ok;

  if (variant === 'card') return renderCard(facts);
  if (variant === 'mark') {
    return face({ label: 'LEDGER', subject: subjectFor('signed activity snapshot'), asOf: facts.asOf }, facts);
  }
  return face(
    {
      label: 'LEDGER',
      subject: subjectFor(`${facts.activeDays} active AI-work ${plural(facts.activeDays, 'day', 'days')}`),
      asOf: facts.asOf,
    },
    facts,
  );
}

export const BADGE_FILENAMES: Record<BadgeVariant, string> = {
  inline: 'badge.svg',
  mark: 'badge-mark.svg',
  card: 'badge-card.svg',
};

/** Ready-to-paste embed snippets. `badgeUrl` must be THIS member's badge. */
export function badgeSnippets(
  profileUrl: string,
  badgeUrl: string,
): { markdown: string; html: string } {
  const alt = 'Ledger — signed record of AI-assisted work, verifiable in your browser';
  return {
    markdown: `[![${alt}](${badgeUrl})](${profileUrl})`,
    html: `<a href="${profileUrl}"><img src="${badgeUrl}" alt="${alt}"></a>`,
  };
}
